// <auto-generated />
namespace LumoTrack.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inbox_users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inbox_users));
        
        string IMigrationMetadata.Id
        {
            get { return "201811012335519_inbox_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
