// <auto-generated />
namespace LumoTrack.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adddevicestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddevicestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201811152000024_add-devices-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
